name = "MSSTA"
uuid = "24825735-5140-4dcf-98c0-6955101801e8"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ITensorTDVP = "25707e16-a4db-4a07-99d9-4d67b7af0342"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
#TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
ITensorTDVP = "0.0.4"
ITensors = "^0.3"
SparseIR = "^0.96, 0.97, 1"
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
